### DISCUSSION TITLE
İSE YOKSA düzeni gibi bir düzen HTML'de nasıl kurulur?

### DISCUSSION THREAD

**Discussion by volkantash** [data-deveb/deveb.css#18] [Yazışmalar]
S.a. Ağ tasarımlarımızı yapar iken bir öğenin üstüne imleci getirince görünmez ettiğimiz öğeleri görünür ediyoruz. Aşağıdaki gibi.

```css
.görünmez{ display:none; }
.üstünde.iken:hover .ise-esnek-ser{ display: flex; }
```

Bunu deveb.css'te bir özellik olarak sunmak istiyorum.

```html
<div class="üstünde iken">
  <div>
    <span class="görünmez ise-esnek-ser"></span>
  </div>
</div>
```

Başka yapılar kurmamıza engel yok. Şimdilik bu yapıyı düşünüyorum.
